apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongo-is-writer
spec:
  schedule: "0 0 1 * *"
  startingDeadlineSeconds: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: mongo-is-writer
        spec:
          restartPolicy: OnFailure
          containers:
            - name: mongo-is-writer
              image: registry.gitlab.com/bp-sojka/mppa/mongo-is-writer:latest
              ports:
                - containerPort: 27017
              env:
                - name: MONGO_USER
                  value: root
                - name: MONGO_PASSWORD
                  value: root
                - name: MONGO_ADDRESS
                  value: "mongodb://mongo-replica-set-0.mongo-is-database.mpaa.svc.cluster.local:27017"
                - name: THREAD_NUMBER
                  value: "2"
                - name: SBIRKA_DOCUMENTS_NUMBER
                  value: "10"
              resources:
                requests:
                  memory: "512Mi"  
                  cpu: "500m"      
                limits:
                  memory: "1Gi"    
                  cpu: "1"         